export interface SeedSchool {
  code: string;
  name: string;
  description: string;
  color: string;
  icon: string;
  order: number;
}

export interface SeedProgram {
  code: string;
  name: string;
  schoolCode: string;
  description: string;
  targetLearner: string;
  entryRequirements: string;
  prerequisites: string;
  duration: string;
  contactHours: number;
  learningLevels: string;
  tools: string;
  projects: string;
  capstone: string;
  assessmentCriteria: string;
  competencies: string;
  certification: string;
  careerPathways: string;
  progressionPathway: string;
  status: 'OPEN_FOR_APPLICATION' | 'UPCOMING' | 'FULL' | 'CLOSED' | 'DRAFT';
  isFeatured: boolean;
}

export const schoolsData: SeedSchool[] = [
  {
    code: 'CSE',
    name: 'Computing and Software Engineering',
    description: 'Master foundational computer science, modern web technologies, scalable backend architectures, cloud infrastructure, and mobile applications with industry-standard engineering practices.',
    color: '#2563eb', // Engineering Blue
    icon: 'Code2',
    order: 1
  },
  {
    code: 'AIDM',
    name: 'Artificial Intelligence, Data and Machine Learning',
    description: 'Transform raw data into predictive intelligence. Explore machine learning algorithms, deep learning, computer vision, natural language processing, and cutting-edge Generative AI applications.',
    color: '#e11d48', // Science Red
    icon: 'BrainCircuit',
    order: 2
  },
  {
    code: 'RIOTH',
    name: 'Robotics, IoT, Embedded Systems and Hardware',
    description: 'Bridge software with the physical world. Design intelligent robotics, IoT sensor networks, embedded microcontrollers, custom PCB circuits, 3D prototypes, and drone systems.',
    color: '#16a34a', // Tech Green
    icon: 'Cpu',
    order: 3
  },
  {
    code: 'RETE',
    name: 'Renewable Energy and Technical Engineering',
    description: 'Power the future with clean energy engineering. Practical training in solar PV installation, inverter sizing, microgrid storage, smart energy automation, and technical electrical systems.',
    color: '#d97706', // Math Amber
    icon: 'SunMedium',
    order: 4
  },
  {
    code: 'DMAP',
    name: 'Digital Media, Marketing and AI Productivity',
    description: 'Supercharge creative media and growth marketing using AI. Learn high-impact video production, visual design, AI-assisted content creation, workflow automation, and vibe coding.',
    color: '#8b5cf6', // Creative Violet
    icon: 'Sparkles',
    order: 5
  },
  {
    code: 'BIE',
    name: 'Business, Innovation and Entrepreneurship',
    description: 'Turn technology breakthroughs into scalable ventures. Practical modules on startup incubation, product management, market validation, digital business, and remote global careers.',
    color: '#0d9488', // Teal
    icon: 'TrendingUp',
    order: 6
  },
  {
    code: 'SKT',
    name: 'STEMPACT Kids and Teens',
    description: 'Inspiring future innovators aged 7–17 through interactive block coding, Python, robotics kits, digital arts, game development, and fun practical invention challenges.',
    color: '#f97316', // Orange
    icon: 'GraduationCap',
    order: 7
  },
  {
    code: 'ISL',
    name: 'Innovation and Startup Lab',
    description: 'Accelerate multidisciplinary prototypes, compete in international hackathons, develop enterprise MVPs, and transform novel research into market-ready technology products.',
    color: '#0284c7', // Sky Blue
    icon: 'Rocket',
    order: 8
  }
];

export const programsData: SeedProgram[] = [
  // 1. Computing and Software Engineering
  {
    code: 'CSE-01',
    name: 'Computer Science Foundation',
    schoolCode: 'CSE',
    description: 'Rigorous foundation in computer architecture, discrete mathematics, algorithmic problem solving, memory management, and data structures.',
    targetLearner: 'Beginners, university undergraduates, and aspiring computer scientists.',
    entryRequirements: 'Basic computer literacy and secondary school mathematics.',
    prerequisites: 'None',
    duration: '12 Weeks',
    contactHours: 60,
    learningLevels: 'Level 1 (Core Computing), Level 2 (Data Structures & Algorithmic Problem Solving)',
    tools: 'C, Python, Linux Terminal, Git, Visual Studio Code',
    projects: 'Memory-efficient cache simulator, custom CLI shell, file compression tool',
    capstone: 'Custom In-Memory Key-Value Storage Engine with indexing and search',
    assessmentCriteria: 'Weekly problem sets (40%), Mid-term algorithmic exam (25%), Capstone defense (35%)',
    competencies: 'Algorithmic Complexity (Big O), Memory Allocation, Recursion, Bitwise Manipulation',
    certification: 'STEMPACT Certificate in Computer Science Foundations',
    careerPathways: 'Junior Software Engineer, Systems Programmer, CS Undergraduate Accelerator',
    progressionPathway: 'Eligible for Full-Stack Software Engineering or AI & Data Science programs',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'CSE-02',
    name: 'Web Development',
    schoolCode: 'CSE',
    description: 'Build modern, responsive, and interactive websites using HTML5, CSS3, modern JavaScript (ES6+), responsive design, and API consumption.',
    targetLearner: 'Career switchers, entrepreneurs, and high school leavers.',
    entryRequirements: 'Basic computer literacy.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 48,
    learningLevels: 'Level 1: Semantic Markup & CSS Grid/Flexbox, Level 2: Modern JavaScript & REST APIs',
    tools: 'HTML5, CSS3, JavaScript, Tailwind CSS, Git, GitHub, VS Code',
    projects: 'Personal portfolio, local business responsive portal, interactive weather dashboard with API integration',
    capstone: 'Fully responsive dynamic e-commerce catalog with cart and state management',
    assessmentCriteria: 'Practical mini-projects (50%), Code reviews (20%), Final project defense (30%)',
    competencies: 'DOM Manipulation, Responsive UI, Asynchronous JS, Version Control, CSS Architecture',
    certification: 'STEMPACT Certified Web Developer',
    careerPathways: 'Junior Frontend Developer, Web Designer, Freelance Web Specialist',
    progressionPathway: 'Full-Stack Software Engineering or Mobile Application Development',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'CSE-03',
    name: 'Software Development',
    schoolCode: 'CSE',
    description: 'Deep dive into object-oriented programming, software architecture principles, test-driven development, and relational database management.',
    targetLearner: 'Learners with basic programming knowledge wanting enterprise-grade coding discipline.',
    entryRequirements: 'Basic coding familiarity in Python, JavaScript, or C.',
    prerequisites: 'Computer Science Foundation or Web Development',
    duration: '14 Weeks',
    contactHours: 72,
    learningLevels: 'Level 1: OOP & SOLID Principles, Level 2: Database Design & Backend Frameworks',
    tools: 'TypeScript, Node.js, PostgreSQL, Docker, Jest, Postman',
    projects: 'Inventory management REST API, banking transaction simulator, automated test suite',
    capstone: 'Enterprise Resource Planning (ERP) backend with JWT auth and audit logging',
    assessmentCriteria: 'API implementations (40%), Database design review (25%), Capstone API architecture (35%)',
    competencies: 'Object-Oriented Design, Relational Normalization, Test-Driven Development, Clean Architecture',
    certification: 'STEMPACT Professional Software Developer Certificate',
    careerPathways: 'Backend Engineer, Software Engineer, API Developer',
    progressionPathway: 'Cloud Computing & DevOps, Full-Stack Software Engineering',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'CSE-04',
    name: 'Full-Stack Software Engineering',
    schoolCode: 'CSE',
    description: 'The flagship immersive engineering program covering end-to-end full-stack development with React, Node.js, TypeScript, PostgreSQL, microservices, and CI/CD pipelines.',
    targetLearner: 'Committed individuals aiming for international remote software engineering careers.',
    entryRequirements: 'Passing score in STEMPACT Technical Assessment or programming prerequisite.',
    prerequisites: 'Diagnostic Placement Test',
    duration: '24 Weeks',
    contactHours: 120,
    learningLevels: 'Level 1: Advanced Frontend & State Management, Level 2: Scalable Backend & Microservices, Level 3: DevOps & Production Deployment',
    tools: 'React, Next.js, Node.js, TypeScript, PostgreSQL, Redis, Docker, AWS, GitHub Actions',
    projects: 'Collaborative real-time task board, distributed payment ledger, automated microservice',
    capstone: 'Complete SaaS Multi-Tenant Platform with Stripe/Paystack billing, notifications, and analytics',
    assessmentCriteria: 'Sprint project milestones (40%), Technical interview & code challenge (30%), Capstone presentation (30%)',
    competencies: 'Full-Stack Architecture, Database Optimization, Microservices, CI/CD, Containerization, System Design',
    certification: 'STEMPACT Advanced Full-Stack Software Engineer Credential',
    careerPathways: 'Full-Stack Engineer, Lead Frontend Engineer, Technical Founder',
    progressionPathway: 'STEMPACT Innovation & Startup Lab Incubator',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'CSE-05',
    name: 'Mobile Application Development',
    schoolCode: 'CSE',
    description: 'Cross-platform native mobile app engineering using React Native and Flutter. Learn offline-first data synchronization, device sensors, push notifications, and app store deployment.',
    targetLearner: 'Developers wanting to build native iOS and Android apps.',
    entryRequirements: 'Solid JavaScript or Dart fundamentals.',
    prerequisites: 'Web Development or equivalent',
    duration: '12 Weeks',
    contactHours: 60,
    learningLevels: 'Level 1: UI Components & Navigation, Level 2: Device Hardware APIs & Offline Storage',
    tools: 'React Native, Flutter, Expo, Firebase, SQLite, Xcode / Android Studio',
    projects: 'Campus transit tracking app, offline healthcare record tracker, fintech wallet UI',
    capstone: 'Production-ready ride-hailing or on-demand logistics mobile application',
    assessmentCriteria: 'Weekly mobile sprint builds (45%), UX performance testing (25%), App store submission readiness (30%)',
    competencies: 'Cross-Platform Architecture, Native Device APIs, State Management, App Store Publishing',
    certification: 'STEMPACT Certified Mobile Developer',
    careerPathways: 'Mobile App Engineer, React Native Specialist, Flutter Developer',
    progressionPathway: 'Innovation Lab or Startup Lab accelerator',
    status: 'UPCOMING',
    isFeatured: false
  },
  {
    code: 'CSE-06',
    name: 'Cloud Computing and DevOps',
    schoolCode: 'CSE',
    description: 'Enterprise cloud infrastructure, container orchestration with Docker and Kubernetes, Infrastructure as Code with Terraform, and robust continuous integration/deployment.',
    targetLearner: 'Backend developers and IT system administrators looking to specialize in cloud infrastructure.',
    entryRequirements: 'Linux CLI proficiency and basic networking knowledge.',
    prerequisites: 'Software Development or Computer Systems',
    duration: '14 Weeks',
    contactHours: 70,
    learningLevels: 'Level 1: Linux & Cloud Fundamentals, Level 2: Containers & Kubernetes, Level 3: CI/CD & Terraform',
    tools: 'AWS, Docker, Kubernetes, Terraform, GitHub Actions, Prometheus, Grafana, Linux',
    projects: 'Multi-region AWS VPC with auto-scaling, GitOps CI/CD pipeline, cluster observability stack',
    capstone: 'Resilient Kubernetes microservice cluster with zero-downtime rolling deployments',
    assessmentCriteria: 'Hands-on infrastructure labs (50%), Cloud architecture exam (25%), Final deployment defense (25%)',
    competencies: 'Infrastructure as Code, Container Orchestration, Site Reliability Engineering, Cloud Security',
    certification: 'STEMPACT Certified Cloud & DevOps Engineer',
    careerPathways: 'DevOps Engineer, Cloud Architect, Site Reliability Engineer (SRE)',
    progressionPathway: 'Senior Infrastructure Consulting',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'CSE-07',
    name: 'Computer Systems and Networking',
    schoolCode: 'CSE',
    description: 'Deep understanding of enterprise local and wide area networks, routing protocols, cybersecurity fundamentals, firewalls, and server operating systems.',
    targetLearner: 'Network engineers, IT officers, and aspiring cybersecurity analysts.',
    entryRequirements: 'Secondary school science / technical diploma.',
    prerequisites: 'None',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Network Protocols & Topologies, Level 2: Subnetting, Routing & Network Security',
    tools: 'Cisco Packet Tracer, Wireshark, Linux, pfSense, Nmap, SSH',
    projects: 'Enterprise LAN design with VLAN segmentation, firewall intrusion detection setup, network packet sniffer',
    capstone: 'Hybrid corporate enterprise secure network architecture with VPN and multi-tier defense',
    assessmentCriteria: 'Lab topology configuration (50%), Troubleshooting scenarios (25%), Final exam (25%)',
    competencies: 'TCP/IP Model, Subnetting, Routing Protocols (OSPF/BGP), Network Hardening, Packet Analysis',
    certification: 'STEMPACT Certified Network Associate',
    careerPathways: 'Network Engineer, Systems Administrator, Cybersecurity Operations Specialist',
    progressionPathway: 'Cloud Computing & DevOps',
    status: 'CLOSED',
    isFeatured: false
  },

  // 2. Artificial Intelligence, Data and Machine Learning
  {
    code: 'AIDM-01',
    name: 'Data Analytics',
    schoolCode: 'AIDM',
    description: 'Transform complex business datasets into actionable insights using advanced Microsoft Excel, Power BI, SQL databases, and exploratory data visualization.',
    targetLearner: 'Business analysts, finance professionals, students, and research fellows.',
    entryRequirements: 'Basic numeracy and computer proficiency.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Excel & Business Intelligence, Level 2: Relational SQL & Power BI Dashboards',
    tools: 'Power BI, Advanced Excel, SQL, Tableau, DAX',
    projects: 'Retail sales performance dashboard, healthcare patient inflow analysis, financial churn report',
    capstone: 'Executive Business Intelligence Suite with automated data pipelines and KPI alerts',
    assessmentCriteria: 'Dashboard presentations (45%), SQL query challenges (30%), Final case study (25%)',
    competencies: 'Data Cleaning, SQL Joins & Aggregations, Data Storytelling, KPI Dashboard Design',
    certification: 'STEMPACT Certified Data Analyst',
    careerPathways: 'Data Analyst, Business Intelligence Developer, Operations Analyst',
    progressionPathway: 'Data Science & Machine Learning',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'AIDM-02',
    name: 'Data Science',
    schoolCode: 'AIDM',
    description: 'Comprehensive data science curriculum: data wrangling, statistical inference, hypothesis testing, predictive modeling, and feature engineering with Python.',
    targetLearner: 'Learners with basic mathematical foundation interested in statistical modeling.',
    entryRequirements: 'High school mathematics / statistics.',
    prerequisites: 'Data Analytics or Python basics',
    duration: '14 Weeks',
    contactHours: 70,
    learningLevels: 'Level 1: Python for Data Science & NumPy/Pandas, Level 2: Statistical Modeling & Scikit-Learn',
    tools: 'Python, Jupyter, Pandas, NumPy, Scikit-Learn, Seaborn, Matplotlib',
    projects: 'House pricing prediction model, customer segmentation cluster, credit default risk classifier',
    capstone: 'End-to-End Predictive Analytics Pipeline with interactive Streamlit web application',
    assessmentCriteria: 'Data modeling notebooks (40%), Statistical theory quiz (20%), Capstone project (40%)',
    competencies: 'Exploratory Data Analysis, Feature Engineering, Regression/Classification, Statistical Inference',
    certification: 'STEMPACT Professional Data Scientist',
    careerPathways: 'Data Scientist, Quantitative Analyst, Machine Learning Researcher',
    progressionPathway: 'Artificial Intelligence and Machine Learning',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'AIDM-03',
    name: 'Artificial Intelligence and Machine Learning',
    schoolCode: 'AIDM',
    description: 'In-depth theory and application of modern machine learning, deep neural networks, convolutional networks, transformers, and reinforcement learning.',
    targetLearner: 'Engineers, computer scientists, and mathematicians wanting to build smart systems.',
    entryRequirements: 'Proficiency in Python and linear algebra.',
    prerequisites: 'Data Science or Computer Science Foundation',
    duration: '16 Weeks',
    contactHours: 80,
    learningLevels: 'Level 1: Supervised & Unsupervised Algorithms, Level 2: Deep Learning & Neural Networks',
    tools: 'PyTorch, TensorFlow, Scikit-Learn, Hugging Face, OpenCV, Python',
    projects: 'Medical image disease classifier, conversational sentiment analyzer, neural recommendation engine',
    capstone: 'Custom Multi-Modal Deep Learning System deployed as an inference API',
    assessmentCriteria: 'Algorithmic implementations (35%), Model benchmarks (25%), Capstone defense (40%)',
    competencies: 'Backpropagation, Neural Architectures, Hyperparameter Tuning, Model Deployment',
    certification: 'STEMPACT AI & Machine Learning Specialist',
    careerPathways: 'AI Engineer, Machine Learning Engineer, Research Scientist',
    progressionPathway: 'Innovation Lab or Startup Lab Incubator',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'AIDM-04',
    name: 'Generative AI and AI Applications',
    schoolCode: 'AIDM',
    description: 'Harness Large Language Models (LLMs), RAG architectures, prompt engineering, fine-tuning, and multi-agent AI systems for real-world enterprise applications.',
    targetLearner: 'Software developers, product innovators, and technical entrepreneurs.',
    entryRequirements: 'Intermediate programming experience in Python or JavaScript.',
    prerequisites: 'Web Development or Python',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: LLM Architecture & Prompt Engineering, Level 2: Vector Databases & RAG Pipelines',
    tools: 'LangChain, LlamaIndex, OpenAI API, Anthropic Claude, ChromaDB, Pinecone, Next.js',
    projects: 'Knowledge base RAG query agent, automated legal contract summarizer, autonomous coding agent',
    capstone: 'Enterprise AI Autonomous Agent System integrating live external tools and databases',
    assessmentCriteria: 'Agent build challenges (40%), RAG evaluation metrics (30%), Final live prototype (30%)',
    competencies: 'Retrieval Augmented Generation, Vector Embeddings, LLM Orchestration, Agent Workflows',
    certification: 'STEMPACT Certified Generative AI Engineer',
    careerPathways: 'Generative AI Specialist, AI Solutions Architect, AI Product Builder',
    progressionPathway: 'Startup Lab / Product Development Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'AIDM-05',
    name: 'Computer Vision',
    schoolCode: 'AIDM',
    description: 'Specialized focus on image processing, object detection, facial recognition, autonomous vehicle perception, and optical character recognition (OCR).',
    targetLearner: 'AI engineers, robotics enthusiasts, and security tech developers.',
    entryRequirements: 'Python programming and basic linear algebra.',
    prerequisites: 'AI & Machine Learning or Python',
    duration: '12 Weeks',
    contactHours: 60,
    learningLevels: 'Level 1: Image Processing & OpenCV, Level 2: YOLO & Deep Convolutional Architectures',
    tools: 'OpenCV, PyTorch, YOLOv8, Albumentations, Roboflow',
    projects: 'License plate recognition system, agricultural crop pest detector, real-time posture analyzer',
    capstone: 'Edge AI Real-Time Object Tracking & Anomaly Detection System on Raspberry Pi',
    assessmentCriteria: 'Detection benchmark labs (40%), Real-time performance (30%), Capstone project (30%)',
    competencies: 'Feature Extraction, Object Segmentation, Transfer Learning, Edge Inference Optimization',
    certification: 'STEMPACT Computer Vision Specialist',
    careerPathways: 'Computer Vision Engineer, Robotics Vision Engineer, AI Surveillance Specialist',
    progressionPathway: 'Robotics and Automation program',
    status: 'UPCOMING',
    isFeatured: false
  },
  {
    code: 'AIDM-06',
    name: 'AI Automation and Intelligent Systems',
    schoolCode: 'AIDM',
    description: 'Automate business workflows by integrating AI models with no-code/low-code tools, webhook orchestrators, web scraping, and robotic process automation (RPA).',
    targetLearner: 'Operations managers, growth engineers, and digital entrepreneurs.',
    entryRequirements: 'Basic computer and internet literacy.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Workflow Orchestration & APIs, Level 2: Custom AI Webhook Automation',
    tools: 'n8n, Zapier, Make, Python, Airtable, OpenAI API',
    projects: 'Automated CRM lead enricher, social media intelligence pipeline, customer support bot',
    capstone: 'Autonomous AI Operations Engine reducing 80% manual data entry for a business',
    assessmentCriteria: 'Automation flow efficiency (50%), Error handling & resilience (25%), Final demo (25%)',
    competencies: 'API Webhooks, RPA, Prompt Automation, Error Handling, Business Process Optimization',
    certification: 'STEMPACT AI Automation Specialist',
    careerPathways: 'AI Automation Consultant, Operations Engineer, Workflow Architect',
    progressionPathway: 'Business, Innovation & Entrepreneurship track',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },

  // 3. Robotics, IoT, Embedded Systems and Hardware
  {
    code: 'RIOTH-01',
    name: 'Robotics and Automation',
    schoolCode: 'RIOTH',
    description: 'Design, build, and program autonomous robots. Master kinematics, actuators, motor drivers, sensor fusion, and ROS (Robot Operating System).',
    targetLearner: 'Engineering students, hardware enthusiasts, and innovators.',
    entryRequirements: 'Basic physics, mathematics, and high school science.',
    prerequisites: 'None',
    duration: '14 Weeks',
    contactHours: 70,
    learningLevels: 'Level 1: Mechanical Design & Actuators, Level 2: Sensor Fusion & ROS Navigation',
    tools: 'ROS2, Arduino, Raspberry Pi, C++, Python, SolidWorks/Fusion 360',
    projects: 'Line-following maze solver, robotic arm manipulator with inverse kinematics, obstacle avoidance rover',
    capstone: 'Autonomous Warehouse Delivery Rover with SLAM mapping and path planning',
    assessmentCriteria: 'Hardware lab builds (50%), ROS simulation exam (20%), Live robotics demonstration (30%)',
    competencies: 'Kinematics, Motor Control, Sensor Fusion, Autonomous Navigation, Microcontroller Programming',
    certification: 'STEMPACT Certified Robotics Engineer',
    careerPathways: 'Robotics Engineer, Automation Specialist, Mechatronics Technician',
    progressionPathway: 'STEMPACT Competition Lab (Robotics Olympiads)',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'RIOTH-02',
    name: 'Internet of Things',
    schoolCode: 'RIOTH',
    description: 'Interconnect devices to the cloud. Build smart environmental monitors, telematics gateways, MQTT broker systems, and low-power wireless sensor networks.',
    targetLearner: 'Smart agriculture practitioners, smart city builders, and hardware developers.',
    entryRequirements: 'Basic programming literacy.',
    prerequisites: 'None',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Sensors & ESP32 Microcontrollers, Level 2: MQTT, Cloud Telemetry & Dashboards',
    tools: 'ESP32, Arduino IDE, MQTT (Mosquitto), Node-RED, InfluxDB, Grafana, AWS IoT Core',
    projects: 'Smart soil moisture irrigation node, air quality telemetry monitor, smart energy meter',
    capstone: 'End-to-End Smart Campus Environmental Monitoring System with live analytics dashboard',
    assessmentCriteria: 'Hardware prototype builds (45%), Cloud telemetry integration (30%), Capstone demo (25%)',
    competencies: 'Wireless Protocols (Wi-Fi, BLE, LoRa), MQTT, Microcontroller Firmware, Cloud Ingestion',
    certification: 'STEMPACT Certified IoT Developer',
    careerPathways: 'IoT Engineer, Embedded Firmware Engineer, Smart Agriculture Technologist',
    progressionPathway: 'Innovation Lab and Hardware Incubator',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'RIOTH-03',
    name: 'Embedded Systems',
    schoolCode: 'RIOTH',
    description: 'Bare-metal microcontroller programming, RTOS (Real-Time Operating Systems), memory-constrained algorithms, communication buses (I2C, SPI, UART, CAN), and debugging.',
    targetLearner: 'Computer and electrical engineering graduates, firmware developers.',
    entryRequirements: 'Understanding of C/C++ programming.',
    prerequisites: 'Computer Science Foundation or Electronics',
    duration: '12 Weeks',
    contactHours: 60,
    learningLevels: 'Level 1: Registers, Peripherals & Bare-Metal C, Level 2: FreeRTOS & Bus Protocols',
    tools: 'STM32 (ARM Cortex-M), Keil / STM32CubeIDE, Logic Analyzers, FreeRTOS, Embedded C',
    projects: 'Custom digital oscilloscope, CAN bus vehicle telemetry reader, multithreaded sensor logger',
    capstone: 'Industrial RTOS Multi-Sensor Monitoring Gateway with secure cryptographic bootloader',
    assessmentCriteria: 'Peripheral driver code (40%), Bus protocol labs (25%), RTOS Capstone presentation (35%)',
    competencies: 'Bare-Metal C, ARM Architecture, FreeRTOS Scheduling, Hardware Interrupts, Low-Power Design',
    certification: 'STEMPACT Professional Embedded Systems Engineer',
    careerPathways: 'Firmware Engineer, Embedded Systems Developer, Automotive Systems Engineer',
    progressionPathway: 'Advanced Hardware Engineering',
    status: 'UPCOMING',
    isFeatured: false
  },
  {
    code: 'RIOTH-04',
    name: 'Electronics and Digital Systems',
    schoolCode: 'RIOTH',
    description: 'Fundamental circuit theory, analog electronics, digital logic design, breadboarding, schematic design, PCB layout, and soldering techniques.',
    targetLearner: 'Beginners passionate about electronics and technical fabrication.',
    entryRequirements: 'Secondary school physics/mathematics.',
    prerequisites: 'None',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Analog Circuits & Components, Level 2: Digital Logic & KiCAD PCB Design',
    tools: 'KiCAD, Multimeter, Oscilloscope, Soldering Station, Circuit Simulator (LTspice)',
    projects: 'Regulated dual power supply, 555-timer frequency generator, audio amplifier circuit',
    capstone: 'Custom 2-Layer Printed Circuit Board (PCB) designed, manufactured, and soldered by student',
    assessmentCriteria: 'Breadboard labs (40%), PCB schematic and layout review (35%), Functional PCB hardware (25%)',
    competencies: 'Schematic Capture, PCB Layout, Soldering, Component Sizing, Oscilloscope Diagnosis',
    certification: 'STEMPACT Certified Electronics Technician',
    careerPathways: 'Electronics Technician, PCB Layout Designer, Hardware Test Engineer',
    progressionPathway: 'Embedded Systems or Solar Installation programs',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'RIOTH-05',
    name: 'Computer Hardware Engineering',
    schoolCode: 'RIOTH',
    description: 'PC building, motherboard diagnostic troubleshooting, chip-level maintenance, BIOS configuration, power delivery systems, and preventative hardware maintenance.',
    targetLearner: 'Technicians, IT hardware support personnel, and hardware repair entrepreneurs.',
    entryRequirements: 'Basic computer literacy.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Hardware Assembly & Architecture, Level 2: Component Diagnostics & Chip-Level Repair',
    tools: 'POST Diagnostic Cards, Soldering Stations, Multimeters, ESD Safe Workbenches',
    projects: 'Custom high-performance PC workstation build, motherboard fault diagnosis and reflow repair',
    capstone: 'Complete refurbishment and performance optimization of multi-generation computer systems',
    assessmentCriteria: 'Assembly speed and accuracy (40%), Diagnostic troubleshooting exam (35%), Safety exam (25%)',
    competencies: 'Hardware Assembly, BIOS Firmware Flashing, Fault Isolation, Thermal Management',
    certification: 'STEMPACT Computer Hardware Specialist',
    careerPathways: 'Hardware Support Engineer, IT Field Technician, Hardware Repair Entrepreneur',
    progressionPathway: 'Renewable Energy or Networking tracks',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'RIOTH-06',
    name: '3D Design and Digital Fabrication',
    schoolCode: 'RIOTH',
    description: 'Computer-Aided Design (CAD), parametric 3D modeling, slicing, FDM/SLA 3D printing, laser cutting, and rapid prototyping for functional engineering parts.',
    targetLearner: 'Makers, product designers, engineering students, and inventors.',
    entryRequirements: 'Spatial visualization interest and computer literacy.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Parametric 3D Modeling (CAD), Level 2: Slicing & Digital Fabrication (3D Printing)',
    tools: 'Autodesk Fusion 360, Cura Slicer, Prusa / Creality 3D Printers, Calipers',
    projects: 'Custom snap-fit electronics enclosure, gear reduction mechanism, ergonomic hand tool grip',
    capstone: 'Fully functional multi-part mechanical prototype fabricated and assembled from scratch',
    assessmentCriteria: 'CAD precision reviews (45%), Slicing & print tolerance tests (30%), Capstone assembly (25%)',
    competencies: 'Parametric CAD Modeling, Tolerancing & Tolerances for 3D Printing, G-Code Generation, Prototyping',
    certification: 'STEMPACT Digital Fabrication Specialist',
    careerPathways: 'Product Design Prototyper, CAD Drafter, Digital Fabrication Lab Technician',
    progressionPathway: 'Innovation Lab Product Prototyping track',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'RIOTH-07',
    name: 'Drone Technology',
    schoolCode: 'RIOTH',
    description: 'UAV aerodynamics, flight controllers, ESC calibration, brushless motors, radio telemetry, autonomous waypoint missions, and safety regulations.',
    targetLearner: 'Aerial survey enthusiasts, precision agriculture practitioners, and drone engineers.',
    entryRequirements: 'Secondary school science foundation.',
    prerequisites: 'Basic Electronics or Robotics familiarity recommended',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Drone Aerodynamics & Assembly, Level 2: Flight Controllers, Telemetry & Autonomous Missions',
    tools: 'Betaflight, Mission Planner, ArduPilot, QGroundControl, Quadcopter Hardware Kits',
    projects: 'FPV quadcopter assembly and tuning, simulated waypoint aerial mapping mission',
    capstone: 'Autonomous GPS-Guided Quadcopter Drone constructed, calibrated, and field-tested by learner',
    assessmentCriteria: 'Hardware assembly inspection (40%), Flight control software tuning (30%), Practical flight test (30%)',
    competencies: 'UAV Electronics, PID Flight Tuning, Autonomous Mission Planning, Safety Regulations',
    certification: 'STEMPACT Certified UAV & Drone Technician',
    careerPathways: 'Drone Technician, UAV Flight Operator, Precision Agriculture Pilot',
    progressionPathway: 'Innovation Lab Aerial Robotics team',
    status: 'UPCOMING',
    isFeatured: true
  },

  // 4. Renewable Energy and Technical Engineering
  {
    code: 'RETE-01',
    name: 'Solar Installation and Renewable Energy',
    schoolCode: 'RETE',
    description: 'Comprehensive hands-on training on photovoltaic (PV) solar panel installation, roof mounting, charge controllers, inverters, deep cycle battery storage, and safety codes.',
    targetLearner: 'Electricians, youth seeking vocational trade skills, engineers, and property managers.',
    entryRequirements: 'Basic electrical familiarity or secondary school technical background.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 48,
    learningLevels: 'Level 1: PV Principles & Solar Hardware, Level 2: Practical Installation & System Commissioning',
    tools: 'Solar Panels, Hybrid Inverters, Lithium / Tubular Batteries, PV Crimpers, Irradiance Meters',
    projects: '500W DC lighting setup, 3.5kVA residential backup system installation, solar water pump setup',
    capstone: 'Live commissioning of a multi-kVA residential solar PV system with safety breaker panel',
    assessmentCriteria: 'Hands-on wiring & mounting drills (50%), Safety compliance test (25%), Commissioning checklist (25%)',
    competencies: 'PV Panel Wiring, Battery Bank Sizing, Inverter Configuration, Earthing & Surge Protection',
    certification: 'STEMPACT Certified Solar PV Installer',
    careerPathways: 'Solar PV Installer, Renewable Energy Technician, Solar Contractor',
    progressionPathway: 'Solar System Design and Engineering',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'RETE-02',
    name: 'Solar System Design and Engineering',
    schoolCode: 'RETE',
    description: 'Advanced solar engineering: load auditing, solar irradiance calculation, shade analysis, commercial system design, string sizing, and CAD single-line electrical diagrams.',
    targetLearner: 'Engineers, technical consultants, and solar project contractors.',
    entryRequirements: 'Technical background or Solar Installation experience.',
    prerequisites: 'Solar Installation or Electrical Engineering foundation',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Load Auditing & Energy Calculations, Level 2: CAD Schematics & Financial Payback Modeling',
    tools: 'PVsyst, Helioscope, AutoCAD Electrical, Excel Load Profilers',
    projects: 'Factory 20kW solar microgrid audit, commercial bank branch solar feasibility study',
    capstone: 'Full engineering design blueprint and financial return model for a 50kW commercial solar mini-grid',
    assessmentCriteria: 'System design calculations (45%), CAD schematic review (30%), Financial model defense (25%)',
    competencies: 'PVsyst Simulation, Single-Line Diagrams, Cable Drop Sizing, LCOE & ROI Calculations',
    certification: 'STEMPACT Solar Design Engineer Credential',
    careerPathways: 'Solar Design Engineer, Energy Consultant, Renewable Energy Project Manager',
    progressionPathway: 'Smart Energy Systems & Innovation Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'RETE-03',
    name: 'Electrical and Electronics Fundamentals',
    schoolCode: 'RETE',
    description: 'Master core principles of single-phase and three-phase AC/DC electrical systems, circuit breakers, conduit wiring, power distribution, transformers, and Nigerian electrical standards.',
    targetLearner: 'Vocational trainees, technical apprentices, and aspiring building services engineers.',
    entryRequirements: 'Secondary school technical or science certificate.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: AC/DC Fundamentals & Circuit Law, Level 2: Building Distribution & Industrial Controls',
    tools: 'Industrial Multimeter, Megger Insulation Tester, Conduit Benders, Contactor Panels',
    projects: 'Domestic two-way lighting circuit board, motor starter circuit with thermal overload relay',
    capstone: 'Complete surface and conduit electrical distribution panel wired to national safety code',
    assessmentCriteria: 'Practical wiring accuracy (50%), Electrical safety test (30%), Theory test (20%)',
    competencies: 'Ohm’s & Kirchhoff’s Laws, Domestic Conduit Wiring, Industrial Motor Starters, Earth Fault Protection',
    certification: 'STEMPACT Certified Electrical Technician',
    careerPathways: 'Domestic Electrician, Industrial Maintenance Technician, Facility Electrician',
    progressionPathway: 'Solar Installation and Renewable Energy',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'RETE-04',
    name: 'Energy Management and Storage',
    schoolCode: 'RETE',
    description: 'In-depth focus on battery chemistry (Lithium Iron Phosphate, Gel, Lead Carbon), Battery Management Systems (BMS), thermal runaway prevention, and commercial energy efficiency.',
    targetLearner: 'Energy managers, facilities directors, and electrical engineers.',
    entryRequirements: 'Basic electrical or solar knowledge.',
    prerequisites: 'Solar Installation or Electrical Fundamentals',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Battery Chemistries & BMS Architecture, Level 2: Energy Auditing & Peak Shaving',
    tools: 'Lithium BMS Interfaces, Battery Capacity Testers, Thermal Imaging Cameras',
    projects: 'Custom 48V 100Ah LiFePO4 battery pack assembly with Bluetooth smart BMS, facility energy audit',
    capstone: 'Commercial Energy Storage System (BESS) optimization project with active load shifting',
    assessmentCriteria: 'Battery pack build testing (45%), Energy audit report (30%), Safety analysis (25%)',
    competencies: 'BMS Calibration, Cell Balancing, Battery Sizing, Energy Auditing, Peak Shaving Strategies',
    certification: 'STEMPACT Energy Storage Specialist',
    careerPathways: 'Energy Storage Engineer, Facilities Energy Auditor, Battery Systems Specialist',
    progressionPathway: 'Smart Energy Systems',
    status: 'UPCOMING',
    isFeatured: false
  },
  {
    code: 'RETE-05',
    name: 'Smart Energy Systems',
    schoolCode: 'RETE',
    description: 'Intersection of clean energy and IoT: intelligent smart meters, remote energy monitoring, automatic transfer switches (ATS), and automated solar microgrid management.',
    targetLearner: 'Engineers seeking to build IoT-connected energy infrastructure.',
    entryRequirements: 'Electronics or IoT basics.',
    prerequisites: 'Solar Installation and IoT or Embedded Systems',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Digital Power Monitoring & Smart Meters, Level 2: Microgrid Automation & Cloud Telemetry',
    tools: 'PZEM Power Meters, ESP32, Modbus Protocol, Home Assistant, Grafana, Cloud Dashboards',
    projects: 'Cloud-connected smart meter with SMS low-credit alerts, automatic generator auto-start controller',
    capstone: 'Self-optimizing microgrid management system balancing solar, grid, and generator power automatically',
    assessmentCriteria: 'System integration & firmware (40%), Cloud telemetry dashboard (35%), Live demonstration (25%)',
    competencies: 'Modbus RS485 Communication, Smart Energy Telemetry, ATS Logic, Automated Load Shedding',
    certification: 'STEMPACT Smart Energy Systems Specialist',
    careerPathways: 'Smart Grid Engineer, Microgrid Automation Specialist, CleanTech Developer',
    progressionPathway: 'Innovation and Startup Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },

  // 5. Digital Media, Marketing and AI Productivity
  {
    code: 'DMAP-01',
    name: 'AI Content Creation',
    schoolCode: 'DMAP',
    description: 'Leverage generative AI to create high-converting multimedia content: copywriting, photorealistic image synthesis, synthesized voiceovers, and dynamic marketing assets.',
    targetLearner: 'Content creators, marketing professionals, agency freelancers, and communications officers.',
    entryRequirements: 'Basic computer and internet literacy.',
    prerequisites: 'None',
    duration: '6 Weeks',
    contactHours: 36,
    learningLevels: 'Level 1: AI Prompt Engineering for Text & Images, Level 2: Multi-Modal AI Production Pipelines',
    tools: 'Midjourney, DALL-E, ChatGPT, ElevenLabs, Claude, RunwayML, Canva',
    projects: 'Brand identity visual style guide, AI-generated documentary voiceover, social media campaign content suite',
    capstone: 'Complete multi-channel multimedia brand launch campaign generated using 100% AI workflows',
    assessmentCriteria: 'Campaign asset quality (50%), Prompt reproducibility portfolio (30%), Presentation (20%)',
    competencies: 'Advanced Prompting, Generative Visual Synthesis, Voice Cloning Ethics, Brand Consistency',
    certification: 'STEMPACT AI Content Specialist',
    careerPathways: 'AI Content Strategist, Digital Media Creator, Creative Director',
    progressionPathway: 'Digital Marketing & Entrepreneurship tracks',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'DMAP-02',
    name: 'Video Production and Editing',
    schoolCode: 'DMAP',
    description: 'Master camera framing, lighting, audio capture, dynamic editing, color grading, visual effects, and AI-accelerated video editing workflows.',
    targetLearner: 'Aspiring videographers, YouTubers, media professionals, and marketing staff.',
    entryRequirements: 'Comfortable with computers.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 48,
    learningLevels: 'Level 1: Cinematic Shooting & Audio, Level 2: Advanced Editing & Color Grading',
    tools: 'Adobe Premiere Pro, DaVinci Resolve, CapCut, Descript, Audacity',
    projects: 'Commercial product commercial video, mini-documentary profile, high-energy social media reel',
    capstone: 'Broadcast-quality 3-minute brand story film produced, edited, and color-graded by learner',
    assessmentCriteria: 'Storytelling & pacing (40%), Technical audio/color polish (35%), Final screening (25%)',
    competencies: 'Non-Linear Editing, Color Correction/Grading, Audio Mastering, B-Roll Storytelling',
    certification: 'STEMPACT Certified Video Editor',
    careerPathways: 'Video Editor, Content Creator, Commercial Videographer, Motion Graphics Artist',
    progressionPathway: 'Freelancing & Remote Careers',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'DMAP-03',
    name: 'Graphic Design and Visual Communication',
    schoolCode: 'DMAP',
    description: 'Principles of design, typography, color theory, layout composition, brand guidelines, print design, and modern digital UI asset creation.',
    targetLearner: 'Creative individuals, branding professionals, and marketers.',
    entryRequirements: 'Basic computer literacy.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 48,
    learningLevels: 'Level 1: Visual Design Principles & Vector Art, Level 2: Comprehensive Branding & Layout',
    tools: 'Adobe Photoshop, Adobe Illustrator, Figma, Canva',
    projects: 'Event promotional poster series, corporate stationery package, editorial magazine layout',
    capstone: 'Complete Corporate Brand Identity System (Logo, Typography, Palette, Brand Manual & Assets)',
    assessmentCriteria: 'Design aesthetics & typography (45%), Brand manual completeness (35%), Client pitch (20%)',
    competencies: 'Typography, Vector Illustration, Brand Guidelines, Visual Hierarchy, Print vs Digital Prep',
    certification: 'STEMPACT Certified Graphic Designer',
    careerPathways: 'Brand Designer, Visual Communicator, Marketing Graphic Artist',
    progressionPathway: 'Digital Marketing or UI/UX Design',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'DMAP-04',
    name: 'Digital Marketing',
    schoolCode: 'DMAP',
    description: 'Data-driven customer acquisition: Search Engine Optimization (SEO), Meta & Google Ads, email marketing automation, conversion rate optimization, and analytics.',
    targetLearner: 'Entrepreneurs, sales professionals, marketing graduates, and freelancers.',
    entryRequirements: 'Basic internet literacy.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Organic Growth (SEO & Content), Level 2: Paid Ads (Meta/Google) & Conversion Funnels',
    tools: 'Meta Ads Manager, Google Ads, Google Analytics 4, Mailchimp, SEMrush',
    projects: 'Local business SEO audit, targeted paid lead generation campaign, automated email nurture sequence',
    capstone: 'End-to-End Growth Marketing Funnel generating verified leads with audited ROI report',
    assessmentCriteria: 'Campaign performance metrics (45%), Marketing plan documentation (30%), Presentation (25%)',
    competencies: 'Paid Ads Management, SEO Audit, Conversion Funnel Optimization, Customer Acquisition Cost',
    certification: 'STEMPACT Certified Digital Marketer',
    careerPathways: 'Digital Marketing Specialist, Growth Marketer, Performance Marketing Lead',
    progressionPathway: 'AI for Digital Marketing & Entrepreneurship',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'DMAP-05',
    name: 'AI for Digital Marketing',
    schoolCode: 'DMAP',
    description: 'Supercharge marketing campaigns using predictive analytics, AI copy generation, automated ad creative variations, sentiment analysis, and smart chatbot funnels.',
    targetLearner: 'Digital marketers and agency owners aiming to multiply output 10x with AI.',
    entryRequirements: 'Familiarity with digital marketing concepts.',
    prerequisites: 'Digital Marketing or equivalent experience',
    duration: '6 Weeks',
    contactHours: 36,
    learningLevels: 'Level 1: AI Copy & Creative Generation, Level 2: Algorithmic Targeting & Predictive Retargeting',
    tools: 'Copy.ai, Jasper, ChatGPT Plus, AdCreative.ai, ManyChat, Python for Marketers',
    projects: '100-variant ad headline A/B test suite, automated Instagram DM lead qualification bot',
    capstone: 'Autonomous AI-Powered Lead Funnel that generates ad creative, copies, and nurtures leads',
    assessmentCriteria: 'A/B testing methodology (40%), Automation bot build (35%), ROI report (25%)',
    competencies: 'AI Ad Optimization, Chatbot Conversation Design, Automated Nurture Funnels, Predictive Analytics',
    certification: 'STEMPACT AI Marketing Strategist',
    careerPathways: 'AI Marketing Consultant, Performance Growth Lead, Agency Automation Specialist',
    progressionPathway: 'Business Innovation and Startup Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'DMAP-06',
    name: 'AI Productivity and Business Automation',
    schoolCode: 'DMAP',
    description: 'Empower executives and corporate teams to multiply daily productivity using AI copilots, automated meeting notes, data extraction, document processing, and executive workflows.',
    targetLearner: 'Professionals, administrators, executives, and business owners.',
    entryRequirements: 'Computer proficiency.',
    prerequisites: 'None',
    duration: '4 Weeks',
    contactHours: 24,
    learningLevels: 'Level 1: Personal AI Copilot Mastery, Level 2: Office & Workflow Process Automation',
    tools: 'Microsoft Copilot, ChatGPT Enterprise, Notion AI, Otter.ai, Zapier, Google Workspace AI',
    projects: 'Executive dashboard with automated report synthesis, automated customer email triage system',
    capstone: 'Personal and organizational AI Operating System eliminating 15+ hours of weekly busywork',
    assessmentCriteria: 'Productivity audit (50%), Workflow demonstration (30%), ROI measurement (20%)',
    competencies: 'AI Document Summarization, Automated Minutes of Meeting, Prompt Systems, Data Synthesis',
    certification: 'STEMPACT AI Productivity Specialist',
    careerPathways: 'Executive Assistant, Productivity Consultant, Operations Lead',
    progressionPathway: 'Business, Innovation and Entrepreneurship',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'DMAP-07',
    name: 'AI for Education',
    schoolCode: 'DMAP',
    description: 'Equip teachers, lecturers, tutors, and academic administrators to design personalized learning materials, automated grading rubrics, STEM simulations, and interactive quizzes.',
    targetLearner: 'Primary, secondary, and tertiary educators, tutors, and school administrators.',
    entryRequirements: 'Teaching or educational administration background.',
    prerequisites: 'None',
    duration: '4 Weeks',
    contactHours: 24,
    learningLevels: 'Level 1: AI Lesson Planning & Materials, Level 2: Differentiated Learning & Assessment Design',
    tools: 'Khanmigo, MagicSchool AI, Curipod, ChatGPT, Quizizz AI, Canva for Education',
    projects: 'Differentiated curriculum unit for varied student speeds, interactive gamified STEM quiz pack',
    capstone: 'Complete term-long AI-Augmented STEM Curriculum Plan with rubric and remediation pathways',
    assessmentCriteria: 'Curriculum pedagogical quality (50%), Assessment rubrics (30%), Peer presentation (20%)',
    competencies: 'Pedagogical Prompting, Differentiated Instruction, Automated Rubric Creation, AI Academic Integrity',
    certification: 'STEMPACT AI Educator Fellow',
    careerPathways: 'EdTech Specialist, Curriculum Lead, Digital Learning Coordinator',
    progressionPathway: 'Partner Schools Network Coordinator',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'DMAP-08',
    name: 'AI-Assisted Development / Vibe Coding',
    schoolCode: 'DMAP',
    description: 'Learn modern AI-first software engineering: conversational coding, rapid prototyping with Cursor, Claude Dev, GitHub Copilot, Replit, and transforming ideas into functional web apps in hours.',
    targetLearner: 'Entrepreneurs, product managers, designers, and non-traditional developers.',
    entryRequirements: 'Basic tech familiarity and problem-solving mindset.',
    prerequisites: 'None',
    duration: '6 Weeks',
    contactHours: 36,
    learningLevels: 'Level 1: AI-Assisted Prototyping & Context Engineering, Level 2: Full-Stack App Assembly with AI',
    tools: 'Cursor AI, GitHub Copilot, Claude 3.5 Sonnet, v0.dev, Supabase, Vercel',
    projects: 'Interactive personal finance tracker built via conversational prompts, custom quiz web app',
    capstone: 'Production-ready full-stack web application conceived, built, and deployed in 48 hours using AI',
    assessmentCriteria: 'Prompt clarity & context scaffolding (40%), App functionality & UX (40%), Live deployment (20%)',
    competencies: 'AI-Assisted Debugging, Context Window Management, Component Assembly, Rapid Prototyping',
    certification: 'STEMPACT AI-Assisted Developer Credential',
    careerPathways: 'AI Prototyper, Technical Product Manager, Indie Hacker, Startup Founder',
    progressionPathway: 'Startup Lab and Product Development Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },

  // 6. Business, Innovation and Entrepreneurship
  {
    code: 'BIE-01',
    name: 'Entrepreneurship and Business Development',
    schoolCode: 'BIE',
    description: 'From idea to sustainable enterprise: customer discovery, business model canvas, financial projections, legal incorporation, sales psychology, and operational scaling in Nigeria.',
    targetLearner: 'Aspiring business owners, SME leaders, and innovators.',
    entryRequirements: 'Entrepreneurial drive and high school completion.',
    prerequisites: 'None',
    duration: '10 Weeks',
    contactHours: 50,
    learningLevels: 'Level 1: Idea Validation & Business Modeling, Level 2: Financial Planning & Go-To-Market Execution',
    tools: 'Business Model Canvas, Lean Canvas, Excel Financial Models, Pitch Decks',
    projects: 'Market customer discovery interview synthesis, 3-year cash flow forecasting model',
    capstone: 'Comprehensive Bankable Business Plan defended before a panel of enterprise mentors',
    assessmentCriteria: 'Market validation data (40%), Financial rigor (30%), Final investor pitch (30%)',
    competencies: 'Customer Validation, Unit Economics, Go-to-Market Strategy, Regulatory Compliance',
    certification: 'STEMPACT Certified Entrepreneur',
    careerPathways: 'Business Founder, Enterprise Development Officer, SME Manager',
    progressionPathway: 'STEMPACT Startup Lab Incubator',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'BIE-02',
    name: 'Innovation and Product Development',
    schoolCode: 'BIE',
    description: 'Design thinking, user research, agile product management, MVP feature prioritization, user journey mapping, and coordinating engineering with market needs.',
    targetLearner: 'Product managers, aspiring founders, and UX designers.',
    entryRequirements: 'Critical thinking and communication skills.',
    prerequisites: 'None',
    duration: '8 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Design Thinking & Discovery, Level 2: Agile Product Management & MVP Launch',
    tools: 'Jira, Trello, Figma, Miro, Notion Product PRDs',
    projects: 'Product Requirements Document (PRD), User journey map, sprint backlog and user story cards',
    capstone: 'Complete Product Strategy & MVP roadmap launch specification for a real-world problem',
    assessmentCriteria: 'PRD quality (40%), User research depth (30%), Prototype walkthrough (30%)',
    competencies: 'Agile/Scrum, User Empathy, PRD Writing, Feature Prioritization (RICE/MoSCoW)',
    certification: 'STEMPACT Certified Product Manager',
    careerPathways: 'Associate Product Manager, Innovation Lead, Scrum Master',
    progressionPathway: 'Startup Lab / Product Development Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'BIE-03',
    name: 'Startup Development',
    schoolCode: 'BIE',
    description: 'Intensive venture builder for high-growth tech startups. Cap table structuring, term sheets, investor pitching, seed fundraising, growth metrics, and scaling.',
    targetLearner: 'Founders with an early-stage prototype or clear tech startup vision.',
    entryRequirements: 'Working prototype or verified market problem.',
    prerequisites: 'Entrepreneurship or technical program completion',
    duration: '12 Weeks',
    contactHours: 60,
    learningLevels: 'Level 1: MVP Traction & Metrics, Level 2: Investor Readiness & Seed Fundraising',
    tools: 'CapTable simulators, DocSend, Loom, Investor Pitch Decks, Stripe/Paystack analytics',
    projects: 'Investor data room setup, 5-minute seed pitch deck, user traction dashboard',
    capstone: 'Live Demo Day pitch presentation to angel investors and seed venture capital partners',
    assessmentCriteria: 'User traction & revenue evidence (50%), Pitch deck clarity (30%), Q&A defense (20%)',
    competencies: 'Fundraising, Term Sheet Negotiation, Growth Loops, Investor Pitching, Legal Structuring',
    certification: 'STEMPACT Startup Founder Fellowship',
    careerPathways: 'Venture-Backed Founder, Startup Executive, Tech Entrepreneur',
    progressionPathway: 'STEMPACT Venture Incubation & Seed Network',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'BIE-04',
    name: 'Freelancing and Remote Careers',
    schoolCode: 'BIE',
    description: 'Unlock global foreign-currency earnings from Nigeria: Upwork profile optimization, international client acquisition, proposal writing, foreign contracts, and global payment channels.',
    targetLearner: 'Skilled developers, designers, writers, and digital workers.',
    entryRequirements: 'Any technical or digital skill from STEMPACT academies.',
    prerequisites: 'Completed at least one technical or digital program',
    duration: '4 Weeks',
    contactHours: 24,
    learningLevels: 'Level 1: Profile Positioning & Portfolio Setup, Level 2: Cold Outreach & Proposal Bidding',
    tools: 'Upwork, Fiverr, LinkedIn, Wise, Payoneer, Contracts & Invoicing templates',
    projects: 'High-converting Upwork profile, targeted video proposal pitch, international contract template',
    capstone: 'First verified international client pitch and contract negotiation executed with instructor mentorship',
    assessmentCriteria: 'Proposal win rate (40%), Portfolio positioning (35%), Mock client interview (25%)',
    competencies: 'High-Ticket Bidding, International Client Management, Cross-Border Payments, Negotiation',
    certification: 'STEMPACT Global Remote Career Specialist',
    careerPathways: 'Independent Global Consultant, Top-Rated Freelancer, Remote Contractor',
    progressionPathway: 'Agency / Studio Development',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'BIE-05',
    name: 'Digital Business and E-Commerce',
    schoolCode: 'BIE',
    description: 'Build, launch, and scale online commerce: Shopify/WooCommerce stores, payment gateway integration (Paystack/Flutterwave), inventory logistics, dropshipping, and digital goods.',
    targetLearner: 'Retailers, e-commerce entrepreneurs, and merchants.',
    entryRequirements: 'Basic computer literacy.',
    prerequisites: 'None',
    duration: '6 Weeks',
    contactHours: 36,
    learningLevels: 'Level 1: Store Setup & Payment Gateways, Level 2: Traffic, Conversion & Logistics Fulfillment',
    tools: 'Shopify, WooCommerce, Paystack, Flutterwave, Klaviyo, Meta Catalog Ads',
    projects: 'Branded online store setup, payment gateway live integration, abandoned cart recovery funnel',
    capstone: 'Fully functional, operational e-commerce store with live products and automated checkout',
    assessmentCriteria: 'Store usability & checkout flow (50%), Marketing plan (30%), Customer journey (20%)',
    competencies: 'E-Commerce UX, Payment Integration, Logistics & Shipping Setup, Conversion Optimization',
    certification: 'STEMPACT E-Commerce Specialist',
    careerPathways: 'E-Commerce Manager, Online Store Owner, E-Commerce Consultant',
    progressionPathway: 'Digital Marketing & Growth tracks',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },

  // 7. STEMPACT Kids and Teens
  {
    code: 'SKT-01',
    name: 'Creative Computing',
    schoolCode: 'SKT',
    description: 'Fun, engaging introduction to computing for kids aged 7–11. Explore how computers think, basic computational logic, safe internet navigation, and creative digital storytelling.',
    targetLearner: 'Children aged 7 to 11 years.',
    entryRequirements: 'Parental enrollment and basic reading skills.',
    prerequisites: 'None',
    duration: '8 Weeks (Saturdays or After-School)',
    contactHours: 32,
    learningLevels: 'Level 1: How Computers Work, Level 2: Digital Creativity & Logical Sequences',
    tools: 'Code.org, Scratch Jr, Tux Paint, TypingClub',
    projects: 'Animated digital postcard, interactive story adventure, safe web research project',
    capstone: 'Digital storybook with sound effects and animated characters presented to parents',
    assessmentCriteria: 'Creativity (40%), Logic understanding (40%), Presentation to class (20%)',
    competencies: 'Computational Thinking, Digital Literacy, Sequential Logic, Online Safety',
    certification: 'STEMPACT Junior Innovator Certificate',
    careerPathways: 'Future Computer Scientists and Engineers',
    progressionPathway: 'Creative Coding and Game Design',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'SKT-02',
    name: 'Creative Coding and Game Design',
    schoolCode: 'SKT',
    description: 'Learn block coding with MIT Scratch and step into Python. Create 2D arcade games, animation reels, interactive quizzes, and understand game mechanics like collision, scoring, and levels.',
    targetLearner: 'Kids and teens aged 9 to 15 years.',
    entryRequirements: 'Parental consent.',
    prerequisites: 'Creative Computing or basic reading/typing',
    duration: '10 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Scratch Block Programming & Sprites, Level 2: Variables, Game Physics & Python Arcade',
    tools: 'MIT Scratch 3.0, Python Turtle, Replit, Pygame Zero',
    projects: 'Space invaders clone, platformer adventure game, animated birthday card with music',
    capstone: 'Original playable multi-level 2D video game showcased at the Junior Demo Day',
    assessmentCriteria: 'Game mechanics & logic (50%), Artwork & creativity (30%), Code structure (20%)',
    competencies: 'Loops, Conditional Logic, Coordinate Systems, Event-Driven Programming, Game Physics',
    certification: 'STEMPACT Junior Game Developer Credential',
    careerPathways: 'Game Designer, Software Developer',
    progressionPathway: 'Young Web Developers or Young AI',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'SKT-03',
    name: 'Young Web Developers',
    schoolCode: 'SKT',
    description: 'Teens aged 12–17 learn to code real websites with HTML, CSS, and basic JavaScript. Build personal portfolios, fan sites, school society pages, and launch them live on GitHub Pages.',
    targetLearner: 'Teens aged 12 to 17 years.',
    entryRequirements: 'Secondary school student with interest in coding.',
    prerequisites: 'Creative Coding or basic typing',
    duration: '10 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: HTML5 & CSS3 Styling, Level 2: Interactive JavaScript & Web Publishing',
    tools: 'HTML5, CSS3, JavaScript, VS Code, GitHub Pages',
    projects: 'Personal teen portfolio, interactive science quiz website, community club webpage',
    capstone: 'Live custom website solving a community or school problem deployed online',
    assessmentCriteria: 'Web page layout (45%), Code neatness (35%), Final presentation (20%)',
    competencies: 'Web Semantics, CSS Layout, Responsive Design for Phones, GitHub Publishing',
    certification: 'STEMPACT Young Web Developer Certificate',
    careerPathways: 'Junior Web Developer, Technology Student',
    progressionPathway: 'Web Development or Full-Stack Engineering',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'SKT-04',
    name: 'Young Robotics and Makers',
    schoolCode: 'SKT',
    description: 'Hands-on robotics for kids and teens: snap circuits, micro:bit programming, sensor tinkering, building smart traffic lights, solar toy buggies, and mini obstacle avoidance robots.',
    targetLearner: 'Kids and teens aged 8 to 16 years.',
    entryRequirements: 'Interest in tinkering and building physical objects.',
    prerequisites: 'None',
    duration: '10 Weeks',
    contactHours: 40,
    learningLevels: 'Level 1: Circuits & BBC micro:bit, Level 2: Motors, Sensors & Rover Assembly',
    tools: 'BBC micro:bit, MakeCode, Snap Circuits, Servo Motors, Ultrasonic Sensors',
    projects: 'Digital compass, step counter, smart plant moisture alarm, mini wheeled robot',
    capstone: 'Autonomous obstacle-avoiding smart rover demonstrated at the STEMPACT Youth Fair',
    assessmentCriteria: 'Mechanical assembly (40%), Code logic (35%), Teamwork & presentation (25%)',
    competencies: 'Hardware Electronics, Microcontroller Coding, Sensor Integration, Problem Solving',
    certification: 'STEMPACT Young Maker & Roboticist',
    careerPathways: 'Roboticist, Mechatronics Engineer, Inventor',
    progressionPathway: 'Robotics and Automation or Drone Technology',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'SKT-05',
    name: 'Young AI and Digital Innovators',
    schoolCode: 'SKT',
    description: 'Demystify Artificial Intelligence for curious teens. Train machine learning models with Teachable Machine, build voice assistants, explore AI art safely, and understand ethics.',
    targetLearner: 'Teens aged 11 to 17 years.',
    entryRequirements: 'Basic computer literacy.',
    prerequisites: 'Creative Coding or Young Web Developers',
    duration: '8 Weeks',
    contactHours: 32,
    learningLevels: 'Level 1: How AI Learns (Vision & Audio), Level 2: Building AI Apps & Ethics',
    tools: 'Google Teachable Machine, App Inventor AI, Scratch AI extensions, Python basics',
    projects: 'Sign language gesture recognizer, smart recycling bin classifier, AI chatbot companion',
    capstone: 'Interactive AI-powered web app that solves a youth or educational problem',
    assessmentCriteria: 'Model accuracy & data collection (40%), App functionality (40%), Ethics awareness (20%)',
    competencies: 'Machine Learning Concepts, Image Classification, Training vs Testing Data, AI Ethics',
    certification: 'STEMPACT Junior AI Innovator',
    careerPathways: 'AI Researcher, Data Scientist, Tech Innovator',
    progressionPathway: 'Data Science or Artificial Intelligence programs',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'SKT-06',
    name: 'Young Entrepreneurs',
    schoolCode: 'SKT',
    description: 'Empower teens to think like founders. Discover problems in their school or community, design simple products, pitch ideas, manage money, and run a mini youth business fair.',
    targetLearner: 'Teens aged 10 to 17 years.',
    entryRequirements: 'Enthusiasm and creative ideas.',
    prerequisites: 'None',
    duration: '6 Weeks',
    contactHours: 24,
    learningLevels: 'Level 1: Problem Finding & Product Design, Level 2: Money Skills, Marketing & Pitching',
    tools: 'Canva, Junior Pitch Decks, Expense Trackers',
    projects: 'Custom handmade or digital product prototype, marketing flyer, 2-minute elevator pitch',
    capstone: 'Live booth at the STEMPACT Young Entrepreneurs Marketplace with real sales to parents & visitors',
    assessmentCriteria: 'Sales and customer interaction (40%), Pitch delivery (35%), Financial ledger (25%)',
    competencies: 'Public Speaking, Financial Literacy, Customer Service, Team Collaboration',
    certification: 'STEMPACT Young Entrepreneur Award',
    careerPathways: 'Future Business Leader, Startup Founder',
    progressionPathway: 'Entrepreneurship & Innovation Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },

  // 8. Innovation and Startup Lab
  {
    code: 'ISL-01',
    name: 'Innovation Lab',
    schoolCode: 'ISL',
    description: 'Multidisciplinary research and rapid physical/digital prototyping laboratory where students, engineers, and researchers collaborate on groundbreaking inventions.',
    targetLearner: 'Advanced students, inventors, alumni, and multidisciplinary teams.',
    entryRequirements: 'Submission of project proposal or academy recommendation.',
    prerequisites: 'Intermediate STEMPACT credential or equivalent',
    duration: 'Ongoing / 16-Week Cycles',
    contactHours: 96,
    learningLevels: 'Sprint 1: Ideation & Feasibility, Sprint 2: Rapid Prototyping, Sprint 3: Validation & Testing',
    tools: 'Digital Fabrication Lab, 3D Printers, Oscilloscopes, Cloud Clusters, IoT Testbenches',
    projects: 'Smart agriculture IoT telemetry node, solar-powered medical refrigeration unit',
    capstone: 'Working physical/digital prototype ready for patent or public deployment',
    assessmentCriteria: 'Engineering rigor (40%), Prototype functionality (40%), Documentation (20%)',
    competencies: 'Rapid Prototyping, Interdisciplinary Engineering, Failure Mode Analysis, Technical Research',
    certification: 'STEMPACT Innovation Lab Fellow',
    careerPathways: 'R&D Engineer, Hardware Innovator, Applied Scientist',
    progressionPathway: 'Startup Lab and Venture Incubation',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'ISL-02',
    name: 'Hackathon Lab',
    schoolCode: 'ISL',
    description: 'High-intensity, time-compressed engineering sprints. Form agile squads, solve corporate and humanitarian challenges in 48 hours, and prepare for national and global hackathons.',
    targetLearner: 'Fast coders, UI designers, data engineers, and problem solvers.',
    entryRequirements: 'Ability to contribute code, design, or business logic.',
    prerequisites: 'Any core track at STEMPACT',
    duration: '4-Week Bootcamp + Weekend Hackathons',
    contactHours: 40,
    learningLevels: 'Level 1: Fast Prototyping Stacks & API Kits, Level 2: Hackathon Strategy, Pitching & Polish',
    tools: 'Supabase, Next.js, Tailwind, Git, Postman, Figma, Pitch Decks',
    projects: '48-hour FinTech micro-lending demo, disaster response alert map, AI emergency dispatcher',
    capstone: 'Live 48-Hour STEMPACT Academy Championship Hackathon with cash prizes and investor showcase',
    assessmentCriteria: 'Completeness of demo (50%), Innovation index (30%), 3-minute pitch (20%)',
    competencies: 'High-Speed Development, Pitch Deck Synthesis, Git Collaboration Under Pressure, API Chaining',
    certification: 'STEMPACT Hackathon Champion Credential',
    careerPathways: 'Hackathon Winner, Tech Lead, Rapid Solutions Architect',
    progressionPathway: 'Competition Lab & Startup Lab',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  },
  {
    code: 'ISL-03',
    name: 'Competition Lab',
    schoolCode: 'ISL',
    description: 'Elite coaching and technical preparation for national and international STEM competitions: International Robotics Olympiads, Kaggle challenges, Huawei ICT, and Science Fairs.',
    targetLearner: 'Top-tier students with exceptional dedication and competitive drive.',
    entryRequirements: 'Invitation or rigorous qualifying technical assessment.',
    prerequisites: 'Top 10% in Academy Assessment or Instructor Recommendation',
    duration: '16 Weeks',
    contactHours: 80,
    learningLevels: 'Phase 1: Deep Theory & Past Problem Analysis, Phase 2: Mock Competitions & Speed Drills',
    tools: 'Kaggle, Codeforces, VEX/FIRST Robotics Kits, Math Olympiad Problem Sets',
    projects: 'Algorithmic contest solver, national robotics competition task rover, machine learning leaderboard model',
    capstone: 'Representation of STEMPACT Academy at national or international competitive finals',
    assessmentCriteria: 'Benchmark competition scores (60%), Speed accuracy (20%), Peer review (20%)',
    competencies: 'Advanced Competitive Programming, Complex Problem Synthesis, Resilience, Precision Robotics',
    certification: 'STEMPACT Elite Competitor Honors',
    careerPathways: 'Olympiad Winner, International Scholar, Lead Research Fellow',
    progressionPathway: 'Global Scholarships and Elite Venture Teams',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'ISL-04',
    name: 'Startup Lab',
    schoolCode: 'ISL',
    description: 'Venture studio inside the academy. Students team up across roles (Founders, Engineers, Data Scientists, Designers, Marketers) to build, test, incorporate, and launch scalable companies.',
    targetLearner: 'Multi-disciplinary student teams ready to build real commercial entities.',
    entryRequirements: 'Cross-functional team or individual with proven technical/business skill.',
    prerequisites: 'Completed an advanced program or equivalent experience',
    duration: '20 Weeks',
    contactHours: 100,
    learningLevels: 'Phase 1: Problem-Solution Fit & MVP Build, Phase 2: User Traction & Seed Pitch',
    tools: 'Stripe, Paystack, Notion, HubSpot, Google Cloud / AWS, Legal Incorporation toolkits',
    projects: 'Live MVP with paying customers, product analytics dashboard, corporate governance bylaws',
    capstone: 'Formal Venture Launch & Investor Pitch Day with active term sheet syndication',
    assessmentCriteria: 'Verified Monthly Recurring Revenue (MRR) or active users (50%), Product stability (30%), Investor readiness (20%)',
    competencies: 'Venture Building, Equity Distribution, Product-Market Fit, Seed Capital Raising',
    certification: 'STEMPACT Venture Incubator Alumnus',
    careerPathways: 'Startup Founder, Chief Technology Officer (CTO), Head of Product',
    progressionPathway: 'STEMPACT Seed Fund & Global Accelerator Applications',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: true
  },
  {
    code: 'ISL-05',
    name: 'Product Development Lab',
    schoolCode: 'ISL',
    description: 'Commercial contract and client-focused engineering lab. Build real software, hardware, and AI products for external enterprise clients, government agencies, and partners.',
    targetLearner: 'Senior students looking for paid real-world client project delivery experience.',
    entryRequirements: 'Portfolio review and instructor recommendation.',
    prerequisites: 'Full-Stack Software Engineering, Hardware, or AI program completion',
    duration: '12 Weeks',
    contactHours: 72,
    learningLevels: 'Stage 1: Client Requirements & Architecture Signoff, Stage 2: Sprint Delivery & Production Handover',
    tools: 'Linear, GitHub, Slack, AWS, Docker, Sentry, Figma',
    projects: 'Local government revenue portal, hospital electronic patient intake tablet system',
    capstone: 'Production client software or hardware deployment with SLA and customer sign-off certificate',
    assessmentCriteria: 'Client satisfaction score (50%), Code quality & tests (30%), On-time delivery (20%)',
    competencies: 'Client Management, SLA Compliance, Production Code Quality, Security Auditing',
    certification: 'STEMPACT Product Engineer Professional',
    careerPathways: 'Consulting Software Engineer, Solutions Architect, Technical Lead',
    progressionPathway: 'Senior Academy Instructor or Tech Consulting Lead',
    status: 'UPCOMING',
    isFeatured: false
  },
  {
    code: 'ISL-06',
    name: 'Research and Experimentation Lab',
    schoolCode: 'ISL',
    description: 'Academic and applied scientific research. Conduct rigorous experiments in applied AI, clean energy storage, decentralized computing, and publish technical papers.',
    targetLearner: 'Academics, university researchers, postgraduate fellows, and deep-tech innovators.',
    entryRequirements: 'Undergraduate degree or strong research proposal.',
    prerequisites: 'Demonstrated technical competency in chosen research domain',
    duration: '24 Weeks',
    contactHours: 120,
    learningLevels: 'Milestone 1: Literature Review & Hypothesis, Milestone 2: Empirical Experimentation & Paper Submission',
    tools: 'LaTeX, Overleaf, arXiv, Python, PyTorch, MATLAB, High-Performance Compute',
    projects: 'Empirical benchmark on local language NLP, thermal efficiency paper on tropical solar PV cooling',
    capstone: 'Co-authored technical research paper submitted to a peer-reviewed conference or journal',
    assessmentCriteria: 'Novelty of methodology (40%), Experimental reproducibility (35%), Peer review evaluation (25%)',
    competencies: 'Scientific Writing, Experimental Design, Statistical Rigor, Literature Synthesis',
    certification: 'STEMPACT Research Fellow Credential',
    careerPathways: 'Applied Research Scientist, PhD Candidate, Deep-Tech Specialist',
    progressionPathway: 'International Research Fellowship',
    status: 'OPEN_FOR_APPLICATION',
    isFeatured: false
  }
];
